/**
 * `sigx zero:extend` — adopt ecosystem packs against an ALREADY-PUBLISHED
 * design system.
 *
 * This is the piece that makes the protocol work across repositories. A
 * design system ships as prebuilt CSS, so an app installing
 * `@sigx/zero-daisyui` and `@acme/zero-stepper` gets no CSS for the stepper —
 * and the design system can never devDepend on every component package that
 * might exist, which is a release-order cycle across repos.
 *
 * The inversion is the one `"sigx-cli"` already uses: the design system
 * depends on nothing, the APP depends on both, and the app is the only place
 * where "which packs do I have" is knowable. So the app recompiles the
 * installed design system against its own discovered packs and keeps the
 * difference.
 *
 * Two facts shape the output.
 *
 * The stylesheet holds ONLY the added scopes. Recipe CSS is already per-scope
 * and self-layered (`@layer zero.recipes`), so load order does not matter —
 * and re-emitting `tokens.css` would duplicate the design system's
 * `@property` registrations and drift its bytes across kit versions.
 *
 * The register module is a REPLACEMENT, not an addition. `ZeroVocabulary` is
 * an interface and every generated register declares `components` as a
 * property, so two modules augmenting it collide with TS2717. The emitted
 * module therefore carries the design system's whole vocabulary plus the
 * packs' scopes, and the app imports it INSTEAD of `@sigx/<ds>/register`.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { auditDesignSystem } from '../audit/index.js';
import { compileDesignSystem } from '../design-system.js';
import type { CompiledDesignSystem, DesignSystemInput } from '../design-system.js';
import { exportedSubpath, installedPackageDir, resolveEcosystem, zeroKitVersion } from '../discover.js';
import { attributeFindings, packagesByScope, whereWithOwner } from '../manifest.js';
import { compileRegisterDts, compileRegisterJs } from '../targets/web/register-dts.js';
import { validateDesignSystem } from '../resolve/validate.js';
import type { CommandEnv } from './shared.js';
import { loadManifest } from './shared.js';

export interface ExtendCommandOptions {
    /** The installed design system to extend, by package name. */
    ds: string;
    /** Directory the artifacts are written to. */
    out: string;
    /** Anatomy manifest (default `@sigx/zero/manifest.json`, from the app). */
    manifest?: string;
    /** Packages to leave out of the adoption. */
    ecosystemExclude?: string[];
}

/**
 * The add-on stylesheet: the added scopes and nothing else.
 *
 * Never the design system's own scopes (it already ships those) and never
 * `tokens.css` — re-emitting that would duplicate its `@property`
 * registrations and drift its bytes across kit versions. Each scope's CSS is
 * self-layered (`@layer zero.recipes`), so this file may be imported in any
 * order relative to the design system's own stylesheet.
 */
export function extendedCss(
    compiled: Pick<CompiledDesignSystem, 'componentCss'>,
    added: readonly string[],
    name: string,
): string {
    return [
        `/* ${name} + ${added.length} ecosystem scope(s), generated by sigx zero:extend. Do not edit. */`,
        ...added.map((scope) => compiled.componentCss[scope] ?? ''),
    ].join('\n');
}

export async function runExtend(env: CommandEnv, opts: ExtendCommandOptions): Promise<void> {
    const dsDir = installedPackageDir(env.cwd, opts.ds);
    if (!dsDir) throw new Error(`[zero-kit] ${opts.ds} is not installed in ${env.cwd}`);
    const dsPkg = JSON.parse(readFileSync(join(dsDir, 'package.json'), 'utf8')) as Record<string, unknown>;

    // The design system's own compiled input, through its public export —
    // resolved by reading the exports map rather than with `require.resolve`,
    // which asks for the `require` condition an ESM package does not declare
    // (`discover.ts` records that dead end at length).
    const subpath = exportedSubpath(dsPkg, './design-system');
    if (!subpath) {
        throw new Error(
            `[zero-kit] ${opts.ds} exports no "./design-system", so it cannot be extended —`
            + ' it needs @sigx/zero-kit 0.3 or newer',
        );
    }
    const entry = resolve(dsDir, subpath);
    const mod = (await import(pathToFileURL(entry).href)) as Record<string, unknown>;
    const designSystem = (mod['designSystem'] ?? mod['default']) as DesignSystemInput | undefined;
    if (!designSystem?.name || !designSystem.tokens) {
        throw new Error(`[zero-kit] ${entry} exports no design system (named "designSystem" or default)`);
    }

    // A design system compiled by a different contract version would be
    // recompiled here by this one, silently producing CSS its own artifacts
    // disagree with.
    const kit = zeroKitVersion();
    try {
        const shippedManifest = exportedSubpath(dsPkg, './manifest.json') ?? './dist/manifest.json';
        const shipped = JSON.parse(readFileSync(resolve(dsDir, shippedManifest), 'utf8')) as { zeroVersion?: string };
        if (kit && shipped.zeroVersion && shipped.zeroVersion !== kit) {
            throw new Error(
                `[zero-kit] ${opts.ds} was built against @sigx/zero ${shipped.zeroVersion} but this project runs ${kit}`
                + ' — install matching versions before extending it',
            );
        }
    } catch (err) {
        // A version mismatch is fatal; an unreadable manifest is not this
        // command's problem to diagnose.
        if (err instanceof Error && err.message.includes('was built against')) throw err;
    }

    const manifest = await loadManifest(env.cwd, opts.manifest);
    const exclude = opts.ecosystemExclude ?? [];
    const resolved = await resolveEcosystem({
        manifest,
        designSystem,
        // The APP's dependencies, not the design system's — that inversion is
        // the whole point of this command.
        ecosystem: { cwd: env.cwd, ...(exclude.length > 0 ? { exclude } : {}) },
        defaultCwd: env.cwd,
        logger: env.logger,
        label: designSystem.name,
    });

    // No early return on an empty set. Writing the pass-through artifacts is
    // what makes a REMOVED pack stop being declared: bailing out would leave
    // the previous run's files in place, still carrying a scope the project
    // no longer installs, and still importable by an app that has no reason
    // to suspect them.
    const added = Object.keys(resolved.contributed).sort();

    const result = validateDesignSystem(resolved.designSystem, resolved.manifest);
    const owners = packagesByScope(resolved.manifest);
    attributeFindings([...result.errors, ...result.warnings], owners);
    for (const issue of [...result.errors, ...result.warnings]) {
        env.logger[issue.level === 'error' ? 'error' : 'warn'](`[${issue.level}] ${whereWithOwner(issue)}: ${issue.message}`);
    }
    if (!result.ok) {
        throw new Error(`[zero-kit] "${designSystem.name}" plus its packs failed validation — nothing written`);
    }

    const compiled = compileDesignSystem(resolved.designSystem, resolved.manifest);

    // The audit runs over the whole thing but only the added scopes are this
    // command's business: the design system's own findings belong to its own
    // build, and repeating them here would read as new.
    const audit = auditDesignSystem(resolved.designSystem, resolved.manifest, { compiled });
    attributeFindings(audit.findings, owners);
    const mine = audit.findings.filter((f) => f.scope !== undefined && added.includes(f.scope));
    for (const finding of mine.filter((f) => f.severity === 'error')) {
        env.logger.warn(`[${designSystem.name}] audit ${finding.rule}: ${whereWithOwner(finding)} — ${finding.message}`);
    }

    const outDir = resolve(env.cwd, opts.out);
    await mkdir(outDir, { recursive: true });

    const cssPath = join(outDir, 'zero-extend.css');
    await writeFile(cssPath, `${extendedCss(compiled, added, designSystem.name)}\n`, 'utf8');

    // A `.d.ts` and its companion `.js`, exactly as a design system's own
    // `/register` ships: the module is types-only, and the runtime file
    // exists so the specifier resolves. Emitting the declaration alone would
    // make the instruction below a lie — importing a `.d.ts` fails in Node
    // and in every bundler.
    const dtsPath = join(outDir, 'zero-extend.d.ts');
    await writeFile(dtsPath, compileRegisterDts(compiled), 'utf8');
    const jsPath = join(outDir, 'zero-extend.js');
    await writeFile(jsPath, compileRegisterJs(compiled), 'utf8');

    env.logger.log(
        added.length > 0
            ? `[${designSystem.name}] extended with ${added.join(', ')}`
            : `[${designSystem.name}] no dependency declares a "sigx-zero" field — wrote pass-through artifacts,`
                + ' which is how a pack removed since the last run stops being declared here',
    );
    env.logger.log(`[${designSystem.name}] wrote ${cssPath}, ${dtsPath} and ${jsPath}`);
    env.logger.log(
        `[${designSystem.name}] import the stylesheet, and import "${opts.out}/zero-extend.js"`
        + ` INSTEAD of "${opts.ds}/register" — remove that import, because augmentations accumulate`
        + ' across a TypeScript program and keeping both declares the same vocabulary twice',
    );
    if (mine.length > 0) {
        env.logger.log(`[${designSystem.name}] ${mine.length} audit finding(s) on the added scope(s)`);
    }
}
