import { defineLibConfig } from '@sigx/vite/lib';

// Unstyled component foundation with subpath exports for tree-shaking.
// One entry per component so a consumer importing `@sigx/zero/tabs` pulls
// nothing else.
export default defineLibConfig({
    entry: {
        'index': 'src/index.ts',
        'anatomy': 'src/anatomy.ts',
        'contract/index': 'src/contract/index.ts',
        'contract/core': 'src/contract/core.ts',
        'behaviors/index': 'src/behaviors/index.ts',
        'behaviors/core': 'src/behaviors/core.ts',
        'adapt/index': 'src/adapt/index.ts',
        'testing/index': 'src/testing/index.ts',
        'theme/index': 'src/theme/index.ts',
        'theme/registry': 'src/theme/registry.ts',
        'components/button/index': 'src/components/button/index.ts',
        'components/tabs/index': 'src/components/tabs/index.ts',
        'components/collapsible/index': 'src/components/collapsible/index.ts',
        'components/switch/index': 'src/components/switch/index.ts',
        'components/dialog/index': 'src/components/dialog/index.ts',
        'components/popover/index': 'src/components/popover/index.ts',
        'components/tooltip/index': 'src/components/tooltip/index.ts',
        'components/menu/index': 'src/components/menu/index.ts',
        'components/field/index': 'src/components/field/index.ts',
        'components/checkbox/index': 'src/components/checkbox/index.ts',
        'components/radio-group/index': 'src/components/radio-group/index.ts',
        'components/progress/index': 'src/components/progress/index.ts',
        'components/slider/index': 'src/components/slider/index.ts',
        'components/accordion/index': 'src/components/accordion/index.ts',
        'components/select/index': 'src/components/select/index.ts',
        'components/avatar/index': 'src/components/avatar/index.ts',
        'components/toast/index': 'src/components/toast/index.ts',
        'components/combobox/index': 'src/components/combobox/index.ts',
        'components/toggle/index': 'src/components/toggle/index.ts',
        'components/toggle-group/index': 'src/components/toggle-group/index.ts',
        'components/number-input/index': 'src/components/number-input/index.ts',
        'components/rating-group/index': 'src/components/rating-group/index.ts',
        'components/tree-view/index': 'src/components/tree-view/index.ts',
        'components/input/index': 'src/components/input/index.ts',
        'components/textarea/index': 'src/components/textarea/index.ts',
        'components/card/index': 'src/components/card/index.ts',
        'components/alert/index': 'src/components/alert/index.ts',
        'components/badge/index': 'src/components/badge/index.ts',
        'components/divider/index': 'src/components/divider/index.ts',
        'components/skeleton/index': 'src/components/skeleton/index.ts',
        'components/stack/index': 'src/components/stack/index.ts',
        'components/spacer/index': 'src/components/spacer/index.ts',
        'components/grid/index': 'src/components/grid/index.ts',
        'components/center/index': 'src/components/center/index.ts',
        'components/box/index': 'src/components/box/index.ts',
        'components/container/index': 'src/components/container/index.ts',
        'components/spinner/index': 'src/components/spinner/index.ts',
        'components/kbd/index': 'src/components/kbd/index.ts',
        'components/status/index': 'src/components/status/index.ts',
        'components/indicator/index': 'src/components/indicator/index.ts',
        'components/stats/index': 'src/components/stats/index.ts',
        'components/timeline/index': 'src/components/timeline/index.ts',
        'components/chat/index': 'src/components/chat/index.ts',
        'components/radial-progress/index': 'src/components/radial-progress/index.ts',
        'components/join/index': 'src/components/join/index.ts',
        'components/navbar/index': 'src/components/navbar/index.ts',
        'components/breadcrumbs/index': 'src/components/breadcrumbs/index.ts',
        'components/pagination/index': 'src/components/pagination/index.ts',
        'components/steps/index': 'src/components/steps/index.ts',
        'components/drawer/index': 'src/components/drawer/index.ts',
        'components/table/index': 'src/components/table/index.ts',
        'components/file-upload/index': 'src/components/file-upload/index.ts',
        'components/carousel/index': 'src/components/carousel/index.ts',
        'components/swap/index': 'src/components/swap/index.ts',
        'components/countdown/index': 'src/components/countdown/index.ts',
        'components/diff/index': 'src/components/diff/index.ts'
    },
    external: ['sigx', 'sigx/jsx-runtime', 'sigx/jsx-dev-runtime'],
    jsx: true
});
