/**
 * The document baseline — an opt-in `html, body` block a design system adds
 * to its `css` (#455).
 *
 * Zero's own CSS stays free of visual design: `@sigx/zero/css/base.css` is
 * layer order and structural fallbacks, nothing that paints. So nothing in
 * zero removes the UA's 8px body margin or puts the skin's ground and type on
 * the page, and an app whose root claims the viewport scrolls by 16px. The
 * design system owns the page's ground and type, so this is where it says
 * so — but only when it asks: it is a helper, not a default.
 *
 * Imported by the `/define` graph, so this module stays `node:`-free.
 */
import { BASE_SURFACE_TOKEN_LIST } from './contract.js';
import type { FontKey, TokensInput } from './tokens.js';

/** The base surfaces a page may stand on. `base-content` is ink, not ground. */
export type DocumentGround = 'base-100' | 'base-200' | 'base-300';

export interface DocumentCssOptions {
    /** The body's background surface. Default `'base-100'`. */
    ground?: DocumentGround;
    /**
     * The typography font key the body is set in. Default `'sans'`. Emitted
     * only when the design system declares that font.
     */
    font?: FontKey;
    /**
     * Give `html` and `body` `block-size: 100%`, so an app root can claim the
     * viewport with a percentage height. Default `true`.
     */
    fullHeight?: boolean;
}

const GROUNDS: readonly string[] = BASE_SURFACE_TOKEN_LIST.filter((t) => t !== 'base-content');

/**
 * The page's margin, ground and type, from this design system's own tokens:
 *
 * ```css
 * html, body { margin: 0; block-size: 100%; }
 * body { background: var(--color-base-100); color: var(--color-base-content); font-family: var(--font-sans); }
 * ```
 *
 * It names only custom properties the design system emits: the base surfaces
 * exist in every theme, and `font-family` is written only when
 * `system.typography.fonts[font]` is declared.
 *
 * No `@layer` of its own. Everything in a design system's `css` lands inside
 * `@layer zero.recipes` in the compiled index.css, so unlayered app CSS still
 * beats this block without a specificity fight.
 */
export function documentCss(tokens: Pick<TokensInput, 'system'>, options: DocumentCssOptions = {}): string {
    const ground = options.ground ?? 'base-100';
    if (!GROUNDS.includes(ground)) {
        throw new Error(`documentCss: ground must be one of ${GROUNDS.join(', ')} (got "${String(ground)}")`);
    }
    const font = options.font ?? 'sans';
    const fullHeight = options.fullHeight ?? true;
    const hasFont = tokens.system?.typography?.fonts?.[font] !== undefined;

    const root = ['margin: 0;', ...(fullHeight ? ['block-size: 100%;'] : [])];
    const body = [
        `background: var(--color-${ground});`,
        'color: var(--color-base-content);',
        ...(hasFont ? [`font-family: var(--font-${font});`] : []),
    ];
    const block = (selector: string, decls: string[]) =>
        `${selector} {\n${decls.map((d) => `    ${d}`).join('\n')}\n}`;

    return [
        '/* The document baseline — generated by @sigx/zero-kit (documentCss).',
        '   The page\'s margin, ground and type, from this design system\'s tokens. */',
        block('html,\nbody', root),
        block('body', body),
    ].join('\n');
}
