/**
 * The design system's breakpoint ramp, reachable from app CSS (#59): the
 * `--breakpoint-*` custom properties on `:root`, and `css/breakpoints.css`'s
 * custom media. The boundaries are `useMediaQuery`'s — `above` is
 * `(min-width: X)`, `below` its exact complement `(width < X)`.
 */
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, describe, expect, it } from 'vitest';
import { anatomies } from '@sigx/zero/anatomy';
import { compileBreakpointsCss, compileDesignSystem, writeArtifacts } from '@sigx/zero-kit';
import type { ManifestComponent } from '@sigx/zero-kit';
import { designSystem as basicDS } from '@sigx/zero-basic';

const manifest = { components: Object.values(anatomies).map((a) => a.toJSON()) as ManifestComponent[] };

const tempDirs: string[] = [];
afterAll(() => {
    for (const dir of tempDirs) rmSync(dir, { recursive: true, force: true });
});

describe('breakpoints in the compiled CSS', () => {
    it('declares --breakpoint-<name> on :root, in declaration order', () => {
        const { tokensCss } = compileDesignSystem(basicDS, manifest);
        const root = tokensCss.slice(tokensCss.indexOf(':where(:root) {'));
        const block = root.slice(0, root.indexOf('}'));
        expect([...block.matchAll(/(--breakpoint-[\w-]+): ([^;]+);/g)].map((m) => [m[1], m[2]])).toEqual([
            ['--breakpoint-sm', '640px'],
            ['--breakpoint-md', '768px'],
            ['--breakpoint-lg', '1024px'],
        ]);
    });

    it('custom media: --above-<name> is the recipe `at` query, --below-<name> its complement', () => {
        expect(compileBreakpointsCss('demo', { md: '48rem', lg: '64rem' })).toBe(
            '/* demo breakpoints — generated by @sigx/zero-kit. Do not edit. */\n'
            + '@custom-media --above-md (min-width: 48rem);\n'
            + '@custom-media --below-md (width < 48rem);\n'
            + '@custom-media --above-lg (min-width: 64rem);\n'
            + '@custom-media --below-lg (width < 64rem);\n',
        );
    });

    it('an empty ramp still yields a file, so the package export always resolves', () => {
        expect(compileBreakpointsCss('demo', {})).toBe('/* demo breakpoints — generated by @sigx/zero-kit. Do not edit. */\n');
    });

    it('writeArtifacts writes css/breakpoints.css', async () => {
        const dir = mkdtempSync(join(tmpdir(), 'zero-breakpoints-'));
        tempDirs.push(dir);
        await writeArtifacts(compileDesignSystem(basicDS, manifest), dir);
        const css = readFileSync(join(dir, 'css', 'breakpoints.css'), 'utf8');
        expect(css).toContain('@custom-media --above-md (min-width: 768px);');
        expect(css).toContain('@custom-media --below-lg (width < 1024px);');
    });
});
