// basic — generated by @sigx/zero-kit. Do not edit.
//
// Augments @sigx/zero's ZeroVocabulary with this design system's compiled
// vocabulary. Opt in with:  import '@sigx/<ds>/register';
declare module '@sigx/zero' {
    interface ZeroVocabulary {
        theme: 'basic' | 'basic-dark';
        breakpoint: 'sm' | 'md' | 'lg';
        property: '--border' | '--color-accent' | '--color-accent-content' | '--color-accent-soft' | '--color-base-100' | '--color-base-200' | '--color-base-300' | '--color-base-content' | '--color-error' | '--color-error-content' | '--color-error-soft' | '--color-info' | '--color-info-content' | '--color-info-soft' | '--color-neutral' | '--color-neutral-content' | '--color-neutral-soft' | '--color-primary' | '--color-primary-content' | '--color-primary-soft' | '--color-secondary' | '--color-secondary-content' | '--color-secondary-soft' | '--color-success' | '--color-success-content' | '--color-success-soft' | '--color-warning' | '--color-warning-content' | '--color-warning-soft' | '--disabled-opacity' | '--duration-fast' | '--duration-normal' | '--duration-slow' | '--ease-exit' | '--ease-standard' | '--font-mono' | '--font-sans' | '--leading-none' | '--leading-normal' | '--leading-tight' | '--measure-lg' | '--measure-md' | '--measure-prose' | '--measure-sm' | '--measure-xl' | '--measure-xs' | '--radius-box' | '--radius-field' | '--radius-selector' | '--shadow-lg' | '--shadow-md' | '--shadow-sm' | '--shadow-xs' | '--size-field' | '--size-selector' | '--space-2xl' | '--space-2xs' | '--space-lg' | '--space-md' | '--space-sm' | '--space-xl' | '--space-xs' | '--text-2xl' | '--text-3xl' | '--text-fixed-2xl' | '--text-fixed-3xl' | '--text-fixed-lg' | '--text-fixed-md' | '--text-fixed-sm' | '--text-fixed-xl' | '--text-fixed-xs' | '--text-lg' | '--text-md' | '--text-sm' | '--text-xl' | '--text-xs' | '--tracking-normal' | '--tracking-tight' | '--tracking-wide' | '--weight-bold' | '--weight-medium' | '--weight-normal' | '--weight-semibold';
        tokens: {
            radius: 'selector' | 'field' | 'box';
            size: 'selector' | 'field';
            font: 'sans' | 'serif' | 'mono' | 'display';
            text: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl';
            weight: 'normal' | 'medium' | 'semibold' | 'bold';
            leading: 'none' | 'tight' | 'normal' | 'relaxed';
            tracking: 'tight' | 'normal' | 'wide';
            space: '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';
            measure: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'prose';
            shadow: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
            duration: 'instant' | 'fast' | 'normal' | 'slow';
            ease: 'linear' | 'standard' | 'emphasized' | 'exit';
        };
        components: {
            /** stack — no axis wired by basic; every axis errors under this register module. */
            'stack': {
                /** Accepts `color` at runtime, but basic declares no color axis for stack — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but basic declares no size axis for stack — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but basic declares no variant axis for stack — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** spacer — no axis wired by basic; every axis errors under this register module. */
            'spacer': {
                /** Accepts `color` at runtime, but basic declares no color axis for spacer — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but basic declares no size axis for spacer — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but basic declares no variant axis for spacer — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** grid — no axis wired by basic; every axis errors under this register module. */
            'grid': {
                /** Accepts `color` at runtime, but basic declares no color axis for grid — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but basic declares no size axis for grid — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but basic declares no variant axis for grid — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** center — no axis wired by basic; every axis errors under this register module. */
            'center': {
                /** Accepts `color` at runtime, but basic declares no color axis for center — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but basic declares no size axis for center — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but basic declares no variant axis for center — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** box — color wired. */
            'box': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                /** Accepts `size` at runtime, but basic declares no size axis for box — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but basic declares no variant axis for box — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** container — no axis wired by basic; every axis errors under this register module. */
            'container': {
                /** Accepts `color` at runtime, but basic declares no color axis for container — the attribute would match nothing. */
                color: never;
                /** Accepts `size` at runtime, but basic declares no size axis for container — the attribute would match nothing. */
                size: never;
                /** Accepts `variant` at runtime, but basic declares no variant axis for container — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** tabs — color, size wired. */
            'tabs': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** collapsible — color, size wired. */
            'collapsible': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** switch — color, size wired. */
            'switch': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** dialog — color, size wired. */
            'dialog': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** popover — color, size wired. */
            'popover': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** tooltip — color, size wired. */
            'tooltip': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** menu — color, size wired. */
            'menu': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** field — color, size wired. */
            'field': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** checkbox — color, size wired. */
            'checkbox': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** radio-group — color, size wired. */
            'radio-group': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** progress — color, size wired. */
            'progress': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** slider — color, size wired. */
            'slider': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** accordion — color, size wired. */
            'accordion': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** select — color, size, variant wired. */
            'select': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                variant: 'outline' | 'soft' | 'ghost';
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** button — color, size, variant wired. */
            'button': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                variant: 'solid' | 'outline' | 'soft' | 'ghost';
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** avatar — color, size wired. */
            'avatar': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** toast — color, size wired. */
            'toast': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** combobox — color, size wired. */
            'combobox': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** toggle — color, size wired. */
            'toggle': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** toggle-group — color, size wired. */
            'toggle-group': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** number-input — color, size wired. */
            'number-input': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** rating-group — color, size wired. */
            'rating-group': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** tree-view — color, size wired. */
            'tree-view': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** input — color, size wired. */
            'input': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** textarea — color, size wired. */
            'textarea': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** card — color, size wired. */
            'card': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** alert — color, size wired. */
            'alert': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** badge — color, size, variant wired. */
            'badge': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                variant: 'solid' | 'soft' | 'outline';
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** divider — color, size wired. */
            'divider': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** skeleton — color, size wired. */
            'skeleton': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** spinner — color, size wired. */
            'spinner': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** kbd — color, size wired. */
            'kbd': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** status — color, size wired. */
            'status': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** indicator — color, size wired. */
            'indicator': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** stats — color, size wired. */
            'stats': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** timeline — color, size wired. */
            'timeline': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** chat — color, size wired. */
            'chat': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** radial-progress — color, size wired. */
            'radial-progress': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** join — color, size wired. */
            'join': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** navbar — color, size wired. */
            'navbar': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** breadcrumbs — color, size wired. */
            'breadcrumbs': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** pagination — color, size wired. */
            'pagination': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** steps — color, size wired. */
            'steps': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** drawer — color, size wired. */
            'drawer': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** table — color, size, mods.hover, mods.zebra wired. */
            'table': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: { 'hover': boolean; 'zebra': boolean };
            };
            /** file-upload — color, size wired. */
            'file-upload': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** carousel — color, size wired. */
            'carousel': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** swap — color, size wired. */
            'swap': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** countdown — color, size wired. */
            'countdown': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
            /** diff — color, size wired. */
            'diff': {
                color: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
                size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
                /** Accepts `variant` at runtime, but no basic recipe wires it — the attribute would match nothing. */
                variant: never;
                axes: Record<string, never>;
                mods: Record<string, never>;
            };
        };
    }
}

// Fails to compile if a scope above is not in zero's anatomy registry
// (a typo or a version skew would otherwise silently take the open
// fallback — docs/architecture.md, "The register artifact").
type _MustBeTrue<T extends true> = T;
type _ScopesValid = _MustBeTrue<
    keyof import('@sigx/zero').ZeroVocabulary['components'] extends import('@sigx/zero').ZeroScope
        ? true : false
>;
// Fails to compile if any entry above drops one of the five members.
// A dropped key is not a smaller entry: the vocabulary resolvers fall
// back to the OPEN union for a member they cannot find, so a truncated
// entry silently un-narrows the axis it omitted (#316).
type _EntryShape = {
    color: string; size: string; variant: string;
    axes: Record<string, string>; mods: Record<string, boolean>;
};
type _Entries = import('@sigx/zero').ZeroVocabulary['components'];
type _EntriesValid = _MustBeTrue<
    { [K in keyof _Entries]: _Entries[K] extends _EntryShape ? true : false }[keyof _Entries] extends true
        ? true : false
>;
export {};
