// heroui — generated by @sigx/zero-kit. Do not edit.
//
// Vendor-named component API (issue #179): zero's components under this
// design system's prop names, narrowed to what its recipes wire.
// Self-contained — nothing here augments ZeroVocabulary, no /register
// import is needed or consulted. The rendered attributes are unchanged:
// a routed vendor value renders the zero-spelled data-* attribute.
import type { Adapted, AdaptedStatics } from '@sigx/zero/adapt';
import type { Stack as ZStack } from '@sigx/zero/stack';
import type { Spacer as ZSpacer } from '@sigx/zero/spacer';
import type { Grid as ZGrid } from '@sigx/zero/grid';
import type { Center as ZCenter } from '@sigx/zero/center';
import type { Box as ZBox } from '@sigx/zero/box';
import type { Container as ZContainer } from '@sigx/zero/container';
import type { Tabs as ZTabs } from '@sigx/zero/tabs';
import type { Collapsible as ZCollapsible } from '@sigx/zero/collapsible';
import type { Switch as ZSwitch } from '@sigx/zero/switch';
import type { Dialog as ZDialog } from '@sigx/zero/dialog';
import type { Popover as ZPopover } from '@sigx/zero/popover';
import type { Tooltip as ZTooltip } from '@sigx/zero/tooltip';
import type { Menu as ZMenu } from '@sigx/zero/menu';
import type { Field as ZField } from '@sigx/zero/field';
import type { Checkbox as ZCheckbox } from '@sigx/zero/checkbox';
import type { RadioGroup as ZRadioGroup } from '@sigx/zero/radio-group';
import type { Progress as ZProgress } from '@sigx/zero/progress';
import type { Slider as ZSlider } from '@sigx/zero/slider';
import type { Accordion as ZAccordion } from '@sigx/zero/accordion';
import type { Select as ZSelect } from '@sigx/zero/select';
import type { Button as ZButton } from '@sigx/zero/button';
import type { Avatar as ZAvatar } from '@sigx/zero/avatar';
import type { Toast as ZToast } from '@sigx/zero/toast';
import type { Combobox as ZCombobox } from '@sigx/zero/combobox';
import type { Toggle as ZToggle } from '@sigx/zero/toggle';
import type { ToggleGroup as ZToggleGroup } from '@sigx/zero/toggle-group';
import type { NumberInput as ZNumberInput } from '@sigx/zero/number-input';
import type { RatingGroup as ZRatingGroup } from '@sigx/zero/rating-group';
import type { TreeView as ZTreeView } from '@sigx/zero/tree-view';
import type { Input as ZInput } from '@sigx/zero/input';
import type { Textarea as ZTextarea } from '@sigx/zero/textarea';
import type { Card as ZCard } from '@sigx/zero/card';
import type { Alert as ZAlert } from '@sigx/zero/alert';
import type { Badge as ZBadge } from '@sigx/zero/badge';
import type { Divider as ZDivider } from '@sigx/zero/divider';
import type { Skeleton as ZSkeleton } from '@sigx/zero/skeleton';
import type { Spinner as ZSpinner } from '@sigx/zero/spinner';
import type { Kbd as ZKbd } from '@sigx/zero/kbd';
import type { Status as ZStatus } from '@sigx/zero/status';
import type { Indicator as ZIndicator } from '@sigx/zero/indicator';
import type { Stats as ZStats } from '@sigx/zero/stats';
import type { Timeline as ZTimeline } from '@sigx/zero/timeline';
import type { Chat as ZChat } from '@sigx/zero/chat';
import type { RadialProgress as ZRadialProgress } from '@sigx/zero/radial-progress';
import type { Join as ZJoin } from '@sigx/zero/join';
import type { Navbar as ZNavbar } from '@sigx/zero/navbar';
import type { Breadcrumbs as ZBreadcrumbs } from '@sigx/zero/breadcrumbs';
import type { Pagination as ZPagination } from '@sigx/zero/pagination';
import type { Steps as ZSteps } from '@sigx/zero/steps';
import type { Drawer as ZDrawer } from '@sigx/zero/drawer';
import type { Table as ZTable } from '@sigx/zero/table';
import type { FileUpload as ZFileUpload } from '@sigx/zero/file-upload';
import type { Carousel as ZCarousel } from '@sigx/zero/carousel';
import type { Swap as ZSwap } from '@sigx/zero/swap';
import type { Countdown as ZCountdown } from '@sigx/zero/countdown';
import type { Diff as ZDiff } from '@sigx/zero/diff';

type ZeroAxisProp = 'color' | 'size' | 'variant' | 'axes' | 'mods';

/** stack — no vendor route; the wired surface keeps zero's names. */
type StackProps = Record<never, never>;
type StackAdapted = Adapted<typeof ZStack, ZeroAxisProp, StackProps>;
export declare const Stack: StackAdapted & AdaptedStatics<typeof ZStack> & { Root: StackAdapted };

/** spacer — no vendor route; the wired surface keeps zero's names. */
type SpacerProps = Record<never, never>;
type SpacerAdapted = Adapted<typeof ZSpacer, ZeroAxisProp, SpacerProps>;
export declare const Spacer: SpacerAdapted & { Root: SpacerAdapted };

/** grid — no vendor route; the wired surface keeps zero's names. */
type GridProps = Record<never, never>;
type GridAdapted = Adapted<typeof ZGrid, ZeroAxisProp, GridProps>;
export declare const Grid: GridAdapted & AdaptedStatics<typeof ZGrid> & { Root: GridAdapted };

/** center — no vendor route; the wired surface keeps zero's names. */
type CenterProps = Record<never, never>;
type CenterAdapted = Adapted<typeof ZCenter, ZeroAxisProp, CenterProps>;
export declare const Center: CenterAdapted & { Root: CenterAdapted };

/** box — no vendor route; the wired surface keeps zero's names. */
type BoxProps = Record<never, never>;
type BoxAdapted = Adapted<typeof ZBox, ZeroAxisProp, BoxProps>;
export declare const Box: BoxAdapted & { Root: BoxAdapted };

/** container — no vendor route; the wired surface keeps zero's names. */
type ContainerProps = Record<never, never>;
type ContainerAdapted = Adapted<typeof ZContainer, ZeroAxisProp, ContainerProps>;
export declare const Container: ContainerAdapted & { Root: ContainerAdapted };

/** tabs — no vendor route; the wired surface keeps zero's names. */
type TabsProps = {
    size?: 'sm' | 'md' | 'lg';
};
type TabsAdapted = Adapted<typeof ZTabs, ZeroAxisProp, TabsProps>;
export declare const Tabs: TabsAdapted & AdaptedStatics<typeof ZTabs> & { Root: TabsAdapted };

/** collapsible — no vendor route; the wired surface keeps zero's names. */
type CollapsibleProps = {
    size?: 'sm' | 'md' | 'lg';
};
type CollapsibleAdapted = Adapted<typeof ZCollapsible, ZeroAxisProp, CollapsibleProps>;
export declare const Collapsible: CollapsibleAdapted & AdaptedStatics<typeof ZCollapsible> & { Root: CollapsibleAdapted };

/** switch — no vendor route; the wired surface keeps zero's names. */
type SwitchProps = {
    size?: 'sm' | 'md' | 'lg';
};
type SwitchAdapted = Adapted<typeof ZSwitch, ZeroAxisProp, SwitchProps>;
export declare const Switch: SwitchAdapted & AdaptedStatics<typeof ZSwitch> & { Root: SwitchAdapted };

/** dialog — no vendor route; the wired surface keeps zero's names. */
type DialogProps = {
    size?: 'sm' | 'md' | 'lg';
};
type DialogAdapted = Adapted<typeof ZDialog, ZeroAxisProp, DialogProps>;
export declare const Dialog: DialogAdapted & AdaptedStatics<typeof ZDialog> & { Root: DialogAdapted };

/** popover — no vendor route; the wired surface keeps zero's names. */
type PopoverProps = {
    size?: 'sm' | 'md' | 'lg';
};
type PopoverAdapted = Adapted<typeof ZPopover, ZeroAxisProp, PopoverProps>;
export declare const Popover: PopoverAdapted & AdaptedStatics<typeof ZPopover> & { Root: PopoverAdapted };

/** tooltip — no vendor route; the wired surface keeps zero's names. */
type TooltipProps = {
    size?: 'sm' | 'md' | 'lg';
};
type TooltipAdapted = Adapted<typeof ZTooltip, ZeroAxisProp, TooltipProps>;
export declare const Tooltip: TooltipAdapted & AdaptedStatics<typeof ZTooltip> & { Root: TooltipAdapted };

/** menu — no vendor route; the wired surface keeps zero's names. */
type MenuProps = {
    size?: 'sm' | 'md' | 'lg';
};
type MenuAdapted = Adapted<typeof ZMenu, ZeroAxisProp, MenuProps>;
export declare const Menu: MenuAdapted & AdaptedStatics<typeof ZMenu> & { Root: MenuAdapted };

/** field — no vendor route; the wired surface keeps zero's names. */
type FieldProps = {
    size?: 'sm' | 'md' | 'lg';
};
type FieldAdapted = Adapted<typeof ZField, ZeroAxisProp, FieldProps>;
export declare const Field: FieldAdapted & AdaptedStatics<typeof ZField> & { Root: FieldAdapted };

/** checkbox — no vendor route; the wired surface keeps zero's names. */
type CheckboxProps = {
    size?: 'sm' | 'md' | 'lg';
};
type CheckboxAdapted = Adapted<typeof ZCheckbox, ZeroAxisProp, CheckboxProps>;
export declare const Checkbox: CheckboxAdapted & AdaptedStatics<typeof ZCheckbox> & { Root: CheckboxAdapted };

/** radio-group — no vendor route; the wired surface keeps zero's names. */
type RadioGroupProps = {
    size?: 'sm' | 'md' | 'lg';
};
type RadioGroupAdapted = Adapted<typeof ZRadioGroup, ZeroAxisProp, RadioGroupProps>;
export declare const RadioGroup: RadioGroupAdapted & AdaptedStatics<typeof ZRadioGroup> & { Root: RadioGroupAdapted };

/** progress — no vendor route; the wired surface keeps zero's names. */
type ProgressProps = {
    size?: 'sm' | 'md' | 'lg';
};
type ProgressAdapted = Adapted<typeof ZProgress, ZeroAxisProp, ProgressProps>;
export declare const Progress: ProgressAdapted & AdaptedStatics<typeof ZProgress> & { Root: ProgressAdapted };

/** slider — no vendor route; the wired surface keeps zero's names. */
type SliderProps = {
    size?: 'sm' | 'md' | 'lg';
};
type SliderAdapted = Adapted<typeof ZSlider, ZeroAxisProp, SliderProps>;
export declare const Slider: SliderAdapted & AdaptedStatics<typeof ZSlider> & { Root: SliderAdapted };

/** accordion — no vendor route; the wired surface keeps zero's names. */
type AccordionProps = {
    size?: 'sm' | 'md' | 'lg';
};
type AccordionAdapted = Adapted<typeof ZAccordion, ZeroAxisProp, AccordionProps>;
export declare const Accordion: AccordionAdapted & AdaptedStatics<typeof ZAccordion> & { Root: AccordionAdapted };

/** select — no vendor route; the wired surface keeps zero's names. */
type SelectProps = {
    size?: 'sm' | 'md' | 'lg';
};
type SelectAdapted = Adapted<typeof ZSelect, ZeroAxisProp, SelectProps>;
export declare const Select: SelectAdapted & AdaptedStatics<typeof ZSelect> & { Root: SelectAdapted };

/** button — variant ← variant; isIconOnly ← mods.icon-only; isPending ← mods.pending. Attributes stay zero-spelled. */
type ButtonProps = {
    size?: 'sm' | 'md' | 'lg';
    'variant'?: 'primary' | 'secondary' | 'tertiary' | 'outline' | 'ghost' | 'danger' | 'danger-soft';
    'isIconOnly'?: boolean;
    'isPending'?: boolean;
};
type ButtonAdapted = Adapted<typeof ZButton, ZeroAxisProp | 'isIconOnly' | 'isPending' | 'variant', ButtonProps>;
export declare const Button: ButtonAdapted & { Root: ButtonAdapted };

/** avatar — no vendor route; the wired surface keeps zero's names. */
type AvatarProps = {
    size?: 'sm' | 'md' | 'lg';
};
type AvatarAdapted = Adapted<typeof ZAvatar, ZeroAxisProp, AvatarProps>;
export declare const Avatar: AvatarAdapted & AdaptedStatics<typeof ZAvatar> & { Root: AvatarAdapted };

/** toast — no vendor route; the wired surface keeps zero's names. */
type ToastProps = {
    size?: 'sm' | 'md' | 'lg';
};
type ToastAdapted = Adapted<typeof ZToast, ZeroAxisProp, ToastProps>;
export declare const Toast: ToastAdapted & AdaptedStatics<typeof ZToast> & { Root: ToastAdapted };

/** combobox — no vendor route; the wired surface keeps zero's names. */
type ComboboxProps = {
    size?: 'sm' | 'md' | 'lg';
};
type ComboboxAdapted = Adapted<typeof ZCombobox, ZeroAxisProp, ComboboxProps>;
export declare const Combobox: ComboboxAdapted & AdaptedStatics<typeof ZCombobox> & { Root: ComboboxAdapted };

/** toggle — no vendor route; the wired surface keeps zero's names. */
type ToggleProps = {
    size?: 'sm' | 'md' | 'lg';
};
type ToggleAdapted = Adapted<typeof ZToggle, ZeroAxisProp, ToggleProps>;
export declare const Toggle: ToggleAdapted & { Root: ToggleAdapted };

/** toggle-group — no vendor route; the wired surface keeps zero's names. */
type ToggleGroupProps = {
    size?: 'sm' | 'md' | 'lg';
};
type ToggleGroupAdapted = Adapted<typeof ZToggleGroup, ZeroAxisProp, ToggleGroupProps>;
export declare const ToggleGroup: ToggleGroupAdapted & AdaptedStatics<typeof ZToggleGroup> & { Root: ToggleGroupAdapted };

/** number-input — no vendor route; the wired surface keeps zero's names. */
type NumberInputProps = {
    size?: 'sm' | 'md' | 'lg';
};
type NumberInputAdapted = Adapted<typeof ZNumberInput, ZeroAxisProp, NumberInputProps>;
export declare const NumberInput: NumberInputAdapted & AdaptedStatics<typeof ZNumberInput> & { Root: NumberInputAdapted };

/** rating-group — no vendor route; the wired surface keeps zero's names. */
type RatingGroupProps = {
    size?: 'sm' | 'md' | 'lg';
};
type RatingGroupAdapted = Adapted<typeof ZRatingGroup, ZeroAxisProp, RatingGroupProps>;
export declare const RatingGroup: RatingGroupAdapted & AdaptedStatics<typeof ZRatingGroup> & { Root: RatingGroupAdapted };

/** tree-view — no vendor route; the wired surface keeps zero's names. */
type TreeViewProps = {
    size?: 'sm' | 'md' | 'lg';
};
type TreeViewAdapted = Adapted<typeof ZTreeView, ZeroAxisProp, TreeViewProps>;
export declare const TreeView: TreeViewAdapted & AdaptedStatics<typeof ZTreeView> & { Root: TreeViewAdapted };

/** input — no vendor route; the wired surface keeps zero's names. */
type InputProps = {
    size?: 'sm' | 'md' | 'lg';
};
type InputAdapted = Adapted<typeof ZInput, ZeroAxisProp, InputProps>;
export declare const Input: InputAdapted & AdaptedStatics<typeof ZInput> & { Root: InputAdapted };

/** textarea — no vendor route; the wired surface keeps zero's names. */
type TextareaProps = {
    size?: 'sm' | 'md' | 'lg';
};
type TextareaAdapted = Adapted<typeof ZTextarea, ZeroAxisProp, TextareaProps>;
export declare const Textarea: TextareaAdapted & AdaptedStatics<typeof ZTextarea> & { Root: TextareaAdapted };

/** card — no vendor route; the wired surface keeps zero's names. */
type CardProps = {
    size?: 'sm' | 'md' | 'lg';
};
type CardAdapted = Adapted<typeof ZCard, ZeroAxisProp, CardProps>;
export declare const Card: CardAdapted & AdaptedStatics<typeof ZCard> & { Root: CardAdapted };

/** alert — no vendor route; the wired surface keeps zero's names. */
type AlertProps = {
    size?: 'sm' | 'md' | 'lg';
};
type AlertAdapted = Adapted<typeof ZAlert, ZeroAxisProp, AlertProps>;
export declare const Alert: AlertAdapted & AdaptedStatics<typeof ZAlert> & { Root: AlertAdapted };

/** badge — no vendor route; the wired surface keeps zero's names. */
type BadgeProps = {
    size?: 'sm' | 'md' | 'lg';
};
type BadgeAdapted = Adapted<typeof ZBadge, ZeroAxisProp, BadgeProps>;
export declare const Badge: BadgeAdapted & { Root: BadgeAdapted };

/** divider — no vendor route; the wired surface keeps zero's names. */
type DividerProps = {
    size?: 'sm' | 'md' | 'lg';
};
type DividerAdapted = Adapted<typeof ZDivider, ZeroAxisProp, DividerProps>;
export declare const Divider: DividerAdapted & { Root: DividerAdapted };

/** skeleton — no vendor route; the wired surface keeps zero's names. */
type SkeletonProps = {
    size?: 'sm' | 'md' | 'lg';
};
type SkeletonAdapted = Adapted<typeof ZSkeleton, ZeroAxisProp, SkeletonProps>;
export declare const Skeleton: SkeletonAdapted & { Root: SkeletonAdapted };

/** spinner — no vendor route; the wired surface keeps zero's names. */
type SpinnerProps = {
    size?: 'sm' | 'md' | 'lg';
};
type SpinnerAdapted = Adapted<typeof ZSpinner, ZeroAxisProp, SpinnerProps>;
export declare const Spinner: SpinnerAdapted & { Root: SpinnerAdapted };

/** kbd — no vendor route; the wired surface keeps zero's names. */
type KbdProps = {
    size?: 'sm' | 'md' | 'lg';
};
type KbdAdapted = Adapted<typeof ZKbd, ZeroAxisProp, KbdProps>;
export declare const Kbd: KbdAdapted & { Root: KbdAdapted };

/** status — no vendor route; the wired surface keeps zero's names. */
type StatusProps = {
    size?: 'sm' | 'md' | 'lg';
};
type StatusAdapted = Adapted<typeof ZStatus, ZeroAxisProp, StatusProps>;
export declare const Status: StatusAdapted & { Root: StatusAdapted };

/** indicator — no vendor route; the wired surface keeps zero's names. */
type IndicatorProps = {
    size?: 'sm' | 'md' | 'lg';
};
type IndicatorAdapted = Adapted<typeof ZIndicator, ZeroAxisProp, IndicatorProps>;
export declare const Indicator: IndicatorAdapted & AdaptedStatics<typeof ZIndicator> & { Root: IndicatorAdapted };

/** stats — no vendor route; the wired surface keeps zero's names. */
type StatsProps = {
    size?: 'sm' | 'md' | 'lg';
};
type StatsAdapted = Adapted<typeof ZStats, ZeroAxisProp, StatsProps>;
export declare const Stats: StatsAdapted & AdaptedStatics<typeof ZStats> & { Root: StatsAdapted };

/** timeline — no vendor route; the wired surface keeps zero's names. */
type TimelineProps = {
    size?: 'sm' | 'md' | 'lg';
};
type TimelineAdapted = Adapted<typeof ZTimeline, ZeroAxisProp, TimelineProps>;
export declare const Timeline: TimelineAdapted & AdaptedStatics<typeof ZTimeline> & { Root: TimelineAdapted };

/** chat — no vendor route; the wired surface keeps zero's names. */
type ChatProps = {
    size?: 'sm' | 'md' | 'lg';
};
type ChatAdapted = Adapted<typeof ZChat, ZeroAxisProp, ChatProps>;
export declare const Chat: ChatAdapted & AdaptedStatics<typeof ZChat> & { Root: ChatAdapted };

/** radial-progress — no vendor route; the wired surface keeps zero's names. */
type RadialProgressProps = {
    size?: 'sm' | 'md' | 'lg';
};
type RadialProgressAdapted = Adapted<typeof ZRadialProgress, ZeroAxisProp, RadialProgressProps>;
export declare const RadialProgress: RadialProgressAdapted & AdaptedStatics<typeof ZRadialProgress> & { Root: RadialProgressAdapted };

/** join — no vendor route; the wired surface keeps zero's names. */
type JoinProps = {
    size?: 'sm' | 'md' | 'lg';
};
type JoinAdapted = Adapted<typeof ZJoin, ZeroAxisProp, JoinProps>;
export declare const Join: JoinAdapted & AdaptedStatics<typeof ZJoin> & { Root: JoinAdapted };

/** navbar — no vendor route; the wired surface keeps zero's names. */
type NavbarProps = {
    size?: 'sm' | 'md' | 'lg';
};
type NavbarAdapted = Adapted<typeof ZNavbar, ZeroAxisProp, NavbarProps>;
export declare const Navbar: NavbarAdapted & AdaptedStatics<typeof ZNavbar> & { Root: NavbarAdapted };

/** breadcrumbs — no vendor route; the wired surface keeps zero's names. */
type BreadcrumbsProps = {
    size?: 'sm' | 'md' | 'lg';
};
type BreadcrumbsAdapted = Adapted<typeof ZBreadcrumbs, ZeroAxisProp, BreadcrumbsProps>;
export declare const Breadcrumbs: BreadcrumbsAdapted & AdaptedStatics<typeof ZBreadcrumbs> & { Root: BreadcrumbsAdapted };

/** pagination — no vendor route; the wired surface keeps zero's names. */
type PaginationProps = {
    size?: 'sm' | 'md' | 'lg';
};
type PaginationAdapted = Adapted<typeof ZPagination, ZeroAxisProp, PaginationProps>;
export declare const Pagination: PaginationAdapted & AdaptedStatics<typeof ZPagination> & { Root: PaginationAdapted };

/** steps — no vendor route; the wired surface keeps zero's names. */
type StepsProps = {
    size?: 'sm' | 'md' | 'lg';
};
type StepsAdapted = Adapted<typeof ZSteps, ZeroAxisProp, StepsProps>;
export declare const Steps: StepsAdapted & AdaptedStatics<typeof ZSteps> & { Root: StepsAdapted };

/** drawer — no vendor route; the wired surface keeps zero's names. */
type DrawerProps = {
    size?: 'sm' | 'md' | 'lg';
};
type DrawerAdapted = Adapted<typeof ZDrawer, ZeroAxisProp, DrawerProps>;
export declare const Drawer: DrawerAdapted & AdaptedStatics<typeof ZDrawer> & { Root: DrawerAdapted };

/** table — isStriped ← mods.striped. Attributes stay zero-spelled. */
type TableProps = {
    size?: 'sm' | 'md' | 'lg';
    'isStriped'?: boolean;
};
type TableAdapted = Adapted<typeof ZTable, ZeroAxisProp | 'isStriped', TableProps>;
export declare const Table: TableAdapted & AdaptedStatics<typeof ZTable> & { Root: TableAdapted };

/** file-upload — no vendor route; the wired surface keeps zero's names. */
type FileUploadProps = {
    size?: 'sm' | 'md' | 'lg';
};
type FileUploadAdapted = Adapted<typeof ZFileUpload, ZeroAxisProp, FileUploadProps>;
export declare const FileUpload: FileUploadAdapted & AdaptedStatics<typeof ZFileUpload> & { Root: FileUploadAdapted };

/** carousel — no vendor route; the wired surface keeps zero's names. */
type CarouselProps = {
    size?: 'sm' | 'md' | 'lg';
};
type CarouselAdapted = Adapted<typeof ZCarousel, ZeroAxisProp, CarouselProps>;
export declare const Carousel: CarouselAdapted & AdaptedStatics<typeof ZCarousel> & { Root: CarouselAdapted };

/** swap — no vendor route; the wired surface keeps zero's names. */
type SwapProps = {
    size?: 'sm' | 'md' | 'lg';
};
type SwapAdapted = Adapted<typeof ZSwap, ZeroAxisProp, SwapProps>;
export declare const Swap: SwapAdapted & AdaptedStatics<typeof ZSwap> & { Root: SwapAdapted };

/** countdown — no vendor route; the wired surface keeps zero's names. */
type CountdownProps = {
    size?: 'sm' | 'md' | 'lg';
};
type CountdownAdapted = Adapted<typeof ZCountdown, ZeroAxisProp, CountdownProps>;
export declare const Countdown: CountdownAdapted & AdaptedStatics<typeof ZCountdown> & { Root: CountdownAdapted };

/** diff — no vendor route; the wired surface keeps zero's names. */
type DiffProps = {
    size?: 'sm' | 'md' | 'lg';
};
type DiffAdapted = Adapted<typeof ZDiff, ZeroAxisProp, DiffProps>;
export declare const Diff: DiffAdapted & AdaptedStatics<typeof ZDiff> & { Root: DiffAdapted };
