// carbon — generated by @sigx/zero-kit. Do not edit.
//
// Vendor-named component API (issue #179): zero's components under this
// design system's prop names, narrowed to what its recipes wire.
// Self-contained — nothing here augments ZeroVocabulary, no /register
// import is needed or consulted. The rendered attributes are unchanged:
// a routed vendor value renders the zero-spelled data-* attribute.
import type { Adapted, AdaptedStatics } from '@sigx/zero/adapt';
import type { Button as ZButton } from '@sigx/zero/button';
import type { Table as ZTable } from '@sigx/zero/table';

type ZeroAxisProp = 'color' | 'size' | 'variant' | 'axes' | 'mods';

/** button — size ← size (2 respelled); buttonKind ← variant. Attributes stay zero-spelled. */
type ButtonProps = {
    'size'?: 'small' | 'medium';
    'buttonKind'?: 'primary' | 'secondary' | 'tertiary' | 'ghost' | 'danger' | 'danger-tertiary' | 'danger-ghost';
    mods?: { 'expressive'?: boolean; 'icon-only'?: boolean };
};
type ButtonAdapted = Adapted<typeof ZButton, ZeroAxisProp | 'buttonKind' | 'size', ButtonProps>;
export declare const Button: ButtonAdapted & { Root: ButtonAdapted };

/** table — no vendor route; the wired surface keeps zero's names. */
type TableProps = {
    mods?: { 'zebra'?: boolean };
};
type TableAdapted = Adapted<typeof ZTable, ZeroAxisProp, TableProps>;
export declare const Table: TableAdapted & AdaptedStatics<typeof ZTable> & { Root: TableAdapted };
