/**
 * `breakpoints.css` — the design system's breakpoint ramp as custom media
 * (Media Queries 5 `@custom-media`), so app CSS names the ramp instead of
 * restating its pixels:
 *
 * ```css
 * @import '@sigx/zero-basic/css/breakpoints';
 * @media (--above-md) { … }   // (min-width: 768px) — what `at: { md }` compiles to
 * @media (--below-md) { … }   // (width < 768px) — its exact complement
 * ```
 *
 * Definitions only, no rules — a separate file rather than a block in
 * `index.css`, because custom media must be resolved by a build step
 * (postcss-custom-media, Lightning CSS `drafts.customMedia`) that SEES the
 * definitions, i.e. the app imports them into its own stylesheet. Importing
 * the whole compiled design system for that would duplicate it.
 *
 * The boundaries are `useMediaQuery`'s (`@sigx/zero`): `above` is
 * `(min-width: X)` and `below` is `(width < X)`, so no width matches both or
 * neither.
 */
export function compileBreakpointsCss(name: string, breakpoints: Record<string, string>): string {
    const lines = [`/* ${name} breakpoints — generated by @sigx/zero-kit. Do not edit. */`];
    for (const [bp, width] of Object.entries(breakpoints)) {
        lines.push(`@custom-media --above-${bp} (min-width: ${width});`);
        lines.push(`@custom-media --below-${bp} (width < ${width});`);
    }
    return `${lines.join('\n')}\n`;
}
