/**
 * The responsive Drawer's per-breakpoint structure (#82) — what makes
 * `modal={{ below: 'md' }}` correct on first paint, before any script runs.
 *
 * The server cannot know the viewport, so a responsive drawer always renders
 * DOCKED: the panel open in markup, the trigger and close present, every one
 * of them stamped `data-l-<bp>-dock="inline"`. Which half is right is a media
 * query's call, and a media query cannot read a custom property — so the
 * rules are emitted here, once per declared breakpoint, from the design
 * system's own ramp. The boundaries are `useMediaQuery`'s and the recipe
 * compiler's: `(min-width: X)` at or above, `(width < X)` below, so no width
 * matches both or neither.
 *
 * - **At or above**: the trigger and close are hidden (there is no sheet to
 *   open, and a docked panel does not close), and the panel is put back in
 *   flow — the UA gives every `<dialog>` `position: absolute` and
 *   `margin: auto`, which is an overlay's geometry, not a sidebar's.
 * - **Below**: the docked panel is hidden unless it is up as a sheet
 *   (`:modal`). A closing sheet loses `:modal` too, which is harmless: the
 *   recipe's `display … allow-discrete` transition holds it through the exit
 *   exactly as it does for the closed-panel rule in `css/base.css`.
 *
 * `@layer zero.structure`, not the recipes' layer: this is how the runtime's
 * behaviour reaches the screen at all, and a skin's ordinary
 * `display: inline-flex` on a trigger must not be able to put it back —
 * `css/base.css`'s reasoning for the `[hidden]` guard.
 */
export function compileDockCss(breakpoints: Readonly<Record<string, string>>): string {
    const entries = Object.entries(breakpoints);
    if (entries.length === 0) return '';
    const part = (name: string, bp: string): string =>
        `[data-scope="drawer"][data-part="${name}"][data-l-${bp}-dock="inline"]`;
    const blocks: string[] = [];
    for (const [bp, width] of entries) {
        blocks.push([
            `    @media (min-width: ${width}) {`,
            `        ${part('trigger', bp)},`,
            `        ${part('close', bp)} {`,
            '            display: none;',
            '        }',
            '',
            `        ${part('panel', bp)} {`,
            '            position: relative;',
            '            inset: auto;',
            '            margin: 0;',
            '        }',
            '    }',
            '',
            `    @media (width < ${width}) {`,
            `        ${part('panel', bp)}:not(:modal) {`,
            '            display: none;',
            '        }',
            '    }',
        ].join('\n'));
    }
    return [
        '/* Responsive Drawer structure (`modal={{ below }}`) — generated by @sigx/zero-kit',
        '   per declared breakpoint; see compileDockCss. */',
        `@layer zero.structure {\n${blocks.join('\n\n')}\n}`,
    ].join('\n');
}
